baseurl = "https://www.xiaotianworld.com/"
languageCode = "en-us"
title = "Xiaotian Tang"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Blogs"
    url = "/Blogs/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "This is the private website for Xiaotian Tang. For research and for fun."
    footer = "&copy; Xiaotian Tang 2018 | [Github](https://github.com/tangxt1) | [Twitter](https://twitter.com/Xiaotian_Tang18?lang=zh-cn)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex"]
  highlightjsTheme = "github"